// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vqbxvsihcxyinqotjacd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZxYnh2c2loY3h5aW5xb3RqYWNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNDA0MTksImV4cCI6MjA2MDgxNjQxOX0.SQelGcnRpS2lSJhLE_ASLUXaoiqmSZHskMcj-5F73nM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);